In [2]:
import pandas as pd

In [9]:
feature_raw_df = pd.read_csv("features_raw.csv")
feature_model_df = pd.read_csv("features_model.csv")

In [6]:
feature_raw_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   node_uuid      6810 non-null   str
 1   node_type      6810 non-null   str
 2   window         6810 non-null   str
 3   out_write      6810 non-null   int64
 4   in_write       6810 non-null   int64
 5   out_read       6810 non-null   int64
 6   in_read        6810 non-null   int64
 7   out_send       6810 non-null   int64
 8   in_send        6810 non-null   int64
 9   out_recv       6810 non-null   int64
 10  in_recv        6810 non-null   int64
 11  out_start      6810 non-null   int64
 12  in_start       6810 non-null   int64
 13  out_load       6810 non-null   int64
 14  in_load        6810 non-null   int64
 15  avg_idle_time  6810 non-null   float64
 16  max_idle_time  6810 non-null   float64
 17  min_idle_time  6810 non-null   float64
 18  n_events       6810 non-null   int64
 19  active_span_s  6810 non-null   float64
dtypes: float64(4), int64(13), str(3)
memory usage: 1.0 MB

In [8]:
feature_raw_df.head()

,node_uuid,node_type,window,out_write,in_write,out_read,in_read,out_send,in_send,out_recv,in_recv,out_start,in_start,out_load,in_load,avg_idle_time,max_idle_time,min_idle_time,n_events,active_span_s
0,w0000_f0038c13cd45eba00,FILE,w0000,0,1,0,0,0,0,0,0,0,0,0,0,0.000000,0.000,0.000,1,0.000
1,w0000_f0094984d5d059671,FILE,w0000,0,0,0,0,0,0,0,0,0,0,0,1,0.000000,0.000,0.000,1,0.000
2,w0000_f00997dd54f13f62f,FILE,w0000,0,0,0,0,0,0,0,0,0,0,0,3,89.618500,157.849,21.388,3,179.237
3,w0000_f00d1150e3e1d8617,FILE,w0000,0,0,0,0,0,0,0,0,0,0,0,4,11.337333,32.807,0.312,4,34.012
4,w0000_f01781b74a305e96e,FILE,w0000,0,0,0,0,0,0,0,0,0,0,0,1,0.000000,0.000,0.000,1,0.000

In [10]:
feature_model_df.head()

,node_uuid,node_type,window,out_write,in_write,out_read,in_read,out_send,in_send,out_recv,in_recv,out_start,in_start,out_load,in_load,avg_idle_time,max_idle_time,min_idle_time
0,w0000_f0038c13cd45eba00,FILE,w0000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
1,w0000_f0094984d5d059671,FILE,w0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000
2,w0000_f00997dd54f13f62f,FILE,w0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.310345,0.544828,0.072414
3,w0000_f00d1150e3e1d8617,FILE,w0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.037931,0.113793,0.000000
4,w0000_f01781b74a305e96e,FILE,w0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000