In [1]:
import pandas as pd

In [3]:
features_raw_df = pd.read_csv("../../artifacts/features/paper/features_raw.csv")
model_df = pd.read_csv("../../artifacts/features/paper/features_model.csv")

In [4]:
features_raw_df.head()

,node_uuid,node_type,window,out_write,in_write,out_read,in_read,out_send,in_send,out_recv,in_recv,out_start,in_start,out_load,in_load,avg_idle_time,max_idle_time,min_idle_time,n_events,active_span_s
0,000189d7ff011419a86f509cbcbce34a,PROCESS,NaN,87,0,20,0,5,0,8,0,0,1,76,0,0.032153,2.003,0.000,197,6.302
1,00059ff798b3bdeeb192eb2d2786baa2,FILE,NaN,0,0,0,20,0,0,0,0,0,0,0,0,4414.267474,32837.858,0.000,20,83871.082
2,000770afc08bef5496dc1a95a67bea76,FILE,NaN,0,3,0,0,0,0,0,0,0,0,0,0,0.000000,0.000,0.000,3,0.000
3,0008292d0c331abafdc40f42474775a0,FILE,NaN,0,0,0,6,0,0,0,0,0,0,0,0,46.791600,231.908,0.089,6,233.958
4,000bd325c12caf5f51a865516fc3e520,FILE,NaN,0,3,0,0,0,0,0,0,0,0,0,0,12.364000,19.268,5.460,3,24.728

In [9]:
model_df.head()

,node_uuid,node_type,window,out_write,in_write,out_read,in_read,out_send,in_send,out_recv,in_recv,out_start,in_start,out_load,in_load,avg_idle_time,max_idle_time,min_idle_time
0,000189d7ff011419a86f509cbcbce34a,PROCESS,NaN,0.739656,0.0,0.170036,0.0,0.042509,0.0,0.068014,0.0,0.0,0.008502,0.646136,0.0,0.000000,0.000020,0.000000
1,00059ff798b3bdeeb192eb2d2786baa2,FILE,NaN,0.000000,0.0,0.000000,1.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.046174,0.331912,0.000000
2,000770afc08bef5496dc1a95a67bea76,FILE,NaN,0.000000,1.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
3,0008292d0c331abafdc40f42474775a0,FILE,NaN,0.000000,0.0,0.000000,1.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000492,0.002345,0.000000
4,000bd325c12caf5f51a865516fc3e520,FILE,NaN,0.000000,1.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000126,0.000192,0.000052