In [2]:
import pandas as pd

In [3]:
ids_2025_df = pd.read_parquet("../../datasets/IDS2025.parquet")
ids_2025_df

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,newLabel
0,50956,443,6,278351,10,5,588,3832,198,0,...,20,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,Normal
1,22,8938,6,2,1,2,0,0,0,0,...,20,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,Normal
2,80,62184,6,24136457,1,5,6,30,6,6,...,20,42392.000,0.000000e+00,42392,42392,24100000.0,0.000000e+00,24100000,24100000,Normal
3,63563,53,17,206,2,2,112,368,56,56,...,32,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,Normal
4,44123,53,17,198,2,2,66,164,33,33,...,20,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91825,1260,444,6,99891716,15,15,5065,90,1460,6,...,20,569902.000,0.000000e+00,569902,569902,98800000.0,0.000000e+00,98800000,98800000,Infiltration
91826,54573,444,6,20,2,0,12,0,6,6,...,20,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,Infiltration
91827,54573,444,6,78233714,48,52,12042,586,1460,0,...,20,2024843.800,3.093999e+06,7461188,3051,13600000.0,1.020000e+07,29500000,5662979,Infiltration
91828,54119,444,6,119995180,1819,1817,489184,10902,1271,6,...,20,5863632.333,4.482322e+06,9355307,809115,14700000.0,1.610000e+07,33200000,5108213,Infiltration
91829,54119,444,6,119991834,5523,5525,2866110,33406,1274,0,...,20,997842.000,8.314713e+05,1585781,409903,8143987.5,1.821774e+06,9432176,6855799,Infiltration

In [11]:
ids_2025_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 91830 entries, 0 to 91829
Data columns (total 80 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Source Port                  91830 non-null  int64
 1   Destination Port             91830 non-null  int64
 2   Protocol                     91830 non-null  int64
 3   Flow Duration                91830 non-null  int64
 4   Total Fwd Packets            91830 non-null  int64
 5   Total Backward Packets       91830 non-null  int64
 6   Total Length of Fwd Packets  91830 non-null  int64
 7   Total Length of Bwd Packets  91830 non-null  int64
 8   Fwd Packet Length Max        91830 non-null  int64
 9   Fwd Packet Length Min        91830 non-null  int64
 10  Fwd Packet Length Mean       91830 non-null  float64
 11  Fwd Packet Length Std        91830 non-null  float64
 12  Bwd Packet Length Max        91830 non-null  int64
 13  Bwd Packet Length Min        91830 non-null  int64
 14  Bwd Packet Length Mean       91830 non-null  float64
 15  Bwd Packet Length Std        91830 non-null  float64
 16  Flow Bytess                  91753 non-null  float64
 17  Flow Packetss                91830 non-null  float64
 18  Flow IAT Mean                91830 non-null  float64
 19  Flow IAT Std                 91830 non-null  float64
 20  Flow IAT Max                 91830 non-null  int64
 21  Flow IAT Min                 91830 non-null  int64
 22  Fwd IAT Total                91830 non-null  int64
 23  Fwd IAT Mean                 91830 non-null  float64
 24  Fwd IAT Std                  91830 non-null  float64
 25  Fwd IAT Max                  91830 non-null  int64
 26  Fwd IAT Min                  91830 non-null  int64
 27  Bwd IAT Total                91830 non-null  int64
 28  Bwd IAT Mean                 91830 non-null  float64
 29  Bwd IAT Std                  91830 non-null  float64
 30  Bwd IAT Max                  91830 non-null  int64
 31  Bwd IAT Min                  91830 non-null  int64
 32  Fwd PSH Flags                91830 non-null  int64
 33  Bwd PSH Flags                91830 non-null  int64
 34  Fwd URG Flags                91830 non-null  int64
 35  Bwd URG Flags                91830 non-null  int64
 36  Fwd Header Length            91830 non-null  int64
 37  Bwd Header Length            91830 non-null  int64
 38  Fwd Packetss                 91830 non-null  float64
 39  Bwd Packetss                 91830 non-null  float64
 40  Min Packet Length            91830 non-null  int64
 41  Max Packet Length            91830 non-null  int64
 42  Packet Length Mean           91830 non-null  float64
 43  Packet Length Std            91830 non-null  float64
 44  Packet Length Variance       91830 non-null  float64
 45  FIN Flag Count               91830 non-null  int64
 46  SYN Flag Count               91830 non-null  int64
 47  RST Flag Count               91830 non-null  int64
 48  PSH Flag Count               91830 non-null  int64
 49  ACK Flag Count               91830 non-null  int64
 50  URG Flag Count               91830 non-null  int64
 51  CWE Flag Count               91830 non-null  int64
 52  ECE Flag Count               91830 non-null  int64
 53  Down Up Ratio                91830 non-null  int64
 54  Average Packet Size          91830 non-null  float64
 55  Avg Fwd Segment Size         91830 non-null  float64
 56  Avg Bwd Segment Size         91830 non-null  float64
 57  Fwd Avg Bytes Bulk           91830 non-null  int64
 58  Fwd Avg Packets Bulk         91830 non-null  int64
 59  Fwd Avg Bulk Rate            91830 non-null  int64
 60  Bwd Avg Bytes Bulk           91830 non-null  int64
 61  Bwd Avg Packets Bulk         91830 non-null  int64
 62  Bwd Avg Bulk Rate            91830 non-null  int64
 63  Subflow Fwd Packets          91830 non-null  int64
 64  Subflow Fwd Bytes            91830 non-null  int64
 65  Subflow Bwd Packets          91830 non-null  int64
 66  Subflow Bwd Bytes            91830 non-null  int64
 67  Init_Win_bytes_forward       91830 non-null  int64
 68  Init_Win_bytes_backward      91830 non-null  int64
 69  act_data_pkt_fwd             91830 non-null  int64
 70  min_seg_size_forward         91830 non-null  int64
 71  Active Mean                  91830 non-null  float64
 72  Active Std                   91830 non-null  float64
 73  Active Max                   91830 non-null  int64
 74  Active Min                   91830 non-null  int64
 75  Idle Mean                    91830 non-null  float64
 76  Idle Std                     91830 non-null  float64
 77  Idle Max                     91830 non-null  int64
 78  Idle Min                     91830 non-null  int64
 79  newLabel                     91830 non-null  object
dtypes: float64(24), int64(55), object(1)
memory usage: 56.0+ MB

In [12]:
ids_2025_df.head()

,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,newLabel
0,50956,443,6,278351,10,5,588,3832,198,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Normal
1,22,8938,6,2,1,2,0,0,0,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Normal
2,80,62184,6,24136457,1,5,6,30,6,6,...,20,42392.0,0.0,42392,42392,24100000.0,0.0,24100000,24100000,Normal
3,63563,53,17,206,2,2,112,368,56,56,...,32,0.0,0.0,0,0,0.0,0.0,0,0,Normal
4,44123,53,17,198,2,2,66,164,33,33,...,20,0.0,0.0,0,0,0.0,0.0,0,0,Normal

In [13]:
ids_2025_df["newLabel"].value_counts()

newLabel
Normal          26185
Dos/DDos        26066
PortScan        25409
Brute Force     10201
Web Attack       2067
Botnet ARES      1873
Infiltration       29
Name: count, dtype: int64